### ISSUE TITLE
Can´t create new Page/Category/Product in Version 3.0.0

### ISSUE THREAD

**Issue by wmdkjozuercher** [magesuite/magesuite#13] opened 2019-08-02 13:06 UTC
**Description**

It's not possible to create a product/category/cms page/cms block.

**Reproduce**

install Magento 2.3.2
set deployment mode to developer
install magesuite 3.0.0
install and activate creativeshop theme
clear cache and open the backend
Try to create a new Page/Category/Product 

**Expected**

Input mask for editing should open.

**Actual**

Category: Input mask is missing
Product: Input mask is missing
CMS Blocks: CMS Block Grid is missing / Input mask for new Block is missing
CMS Pages: CMS Pages Grid is missing / exception is thrown:

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/vendor/creativestyle/magesuite-opengraph/view/adminhtml/ui_component/cms_page_form.xml" is invalid:
Element 'argument': This element is not expected. Expected is one of ( bookmark, boolean, button, checkbox, checkboxset, colorPicker, component, container, dataSource, dataProvider ).
Line: 9

Verify the XML and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/vendor/creativestyle/magesuite-opengraph/view/adminhtml/ui_component/cms_page_form.xml" is invalid:
Element 'argument': This element is not expected. Expected is one of ( bookmark, boolean, button, checkbox, checkboxset, colorPicker, component, container, dataSource, dataProvider ).
Line: 9

Verify the XML and try again.
<pre>#1 Magento\Ui\Config\Reader->read() called at [vendor/magento/module-ui/Config/Data.php:102]
#2 Magento\Ui\Config\Data->initData() called at [vendor/magento/module-ui/Config/Data.php:136]
#3 Magento\Ui\Config\Data->get() called at [vendor/magento/framework/View/Layout/Reader/UiComponent.php:100]
#4 Magento\Framework\View\Layout\Reader\UiComponent->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#5 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Layout/Reader/Container.php:89]
#6 Magento\Framework\View\Layout\Reader\Container->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#7 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Page/Config/Reader/Body.php:68]
#8 Magento\Framework\View\Page\Config\Reader\Body->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#9 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Layout.php:325]
#10 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:89]
#11 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#12 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#13 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#14 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:253]
#15 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:875]
#16 Magento\Framework\View\Layout->getBlock() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:414]
#17 Magento\Framework\View\Layout\Interceptor->getBlock() called at [vendor/magento/module-backend/Model/View/Result/Page.php:26]
#18 Magento\Backend\Model\View\Result\Page->setActiveMenu() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:24]
#19 Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu() called at [vendor/magento/module-cms/Controller/Adminhtml/Page/Edit.php:60]
#20 Magento\Cms\Controller\Adminhtml\Page\Edit->_initAction() called at [vendor/magento/module-cms/Controller/Adminhtml/Page/Edit.php:93]
#21 Magento\Cms\Controller\Adminhtml\Page\Edit->execute() called at [generated/code/Magento/Cms/Controller/Adminhtml/Page/Edit/Interceptor.php:24]
#22 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#23 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#24 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#25 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#26 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#27 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#28 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#29 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Controller/Adminhtml/Page/Edit/Interceptor.php:39]
#30 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#31 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#32 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#33 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#34 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#35 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#36 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:137]
#37 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#38 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#39 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:41]
</pre>
```

As soon as I disable the two Modules the gridview etc. are visible.
The Modules are: **MageSuite_CmsTagManager** and **MageSuite_Opengraph**

**Comment by diwipl** [comment] 2019-08-12 09:53
I am working on providing fix now.

**Comment by diwipl** [comment] 2019-08-12 15:36
> CMS Pages: CMS Pages Grid is missing / exception is thrown:

Should be fixed now.

> Category: Input mask is missing
> Product: Input mask is missing
> CMS Blocks: CMS Block Grid is missing / Input mask for new Block is missing

I was not able to reproduce, can you provide some kind of screenshot/video for that bug?

**Comment by krzksz** [comment] 2019-10-21 07:17
I'm closing this because the fix was provided and there is no further activity. If the issue persists please let us know and this ticket can be reopened.

**Closed as completed by krzksz** 2019-10-21 07:17 UTC
