### ISSUE TITLE
PHP7.4 support

### ISSUE THREAD

**Issue by tritas** [magesuite/magesuite#64] opened 2020-10-28 09:43 UTC
Hi,  thank you for all the work on this project!

This issue is meant to track support for version 7.4.

**Comment by groomershop-mt** [comment] 2020-11-01 17:19
We have just upgraded to Magento 2.4.1 + MageSuite 6.0 + PHP 7.4 and we receive error at main site regarding PHP 7.4:

```
1 exception(s):
Exception #0 (Exception): Deprecated Functionality: implode(): Passing glue string after array is deprecated. Swap the parameters in /home/magento/domains/nowy.groomershop.pl/public_html/vendor/creativestyle/magesuite-content-constructor-frontend/Service/MediaResolver.php on line 181

Exception #0 (Exception): Deprecated Functionality: implode(): Passing glue string after array is deprecated. Swap the parameters in /home/magento/domains/nowy.groomershop.pl/public_html/vendor/creativestyle/magesuite-content-constructor-frontend/Service/MediaResolver.php on line 181
<pre>#1 implode() called at [vendor/creativestyle/magesuite-content-constructor-frontend/Service/MediaResolver.php:181]
#2 MageSuite\ContentConstructorFrontend\Service\MediaResolver->buildSrcSet() called at [vendor/creativestyle/magesuite-content-constructor-frontend/Service/MediaResolver.php:80]
#3 MageSuite\ContentConstructorFrontend\Service\MediaResolver->resolveSrcSet() called at [vendor/creativestyle/magesuite-content-constructor-frontend/Model/Component/ImageTeaser/Slide.php:31]
#4 MageSuite\ContentConstructorFrontend\Model\Component\ImageTeaser\Slide->getSrcSet() called at [vendor/creativestyle/magesuite-content-constructor-frontend/view/frontend/templates/component/image_teaser/slide_elements/image.phtml:14]
#5 include('/home/magento/do...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#6 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/Interception/Interceptor.php:58]
....
```

**Comment by krisdante** [comment] 2020-12-10 22:01
Duplicate of https://github.com/magesuite/magesuite/issues/69

**Closed as completed by krisdante** 2020-12-10 22:01 UTC
