### ISSUE TITLE
Can not see or attach to a configurable product the associated simple products

### ISSUE THREAD

**Issue by daniel-ifrim** [magesuite/magesuite#48] opened 2020-05-15 12:17 UTC
- We have Magesuite with updated packages, maybe not the latest
- Magento 2.3.4

I have simple associated products options on color and size super attributes.
It saves only 12 simple products in admin on configurable product edit page.
Both tables `catalog_product_super_link` and `catalog_product_relation` are fine.
Basically I see in admin in the Configurations grid only 12 products. And I can not add new products to configurations.
The issue happens on the size attribute.
Magento stack trace looks like this:
```
vendor/magento/module-configurable-product/Model/ResourceModel/Product/Type/Configurable/Attribute/Collection.php::loadOptions
vendor/magento/module-configurable-product/Model/ResourceModel/Product/Type/Configurable.php::getAttributeOptions
vendor/magento/module-configurable-product/Model/AttributeOptionProvider.php::getAttributeOptions
```
Method `loadOptions` is used to fetch the "values" of the options into the attribute `size`

```
...
\Magento\ConfigurableProduct\Model\Product\Type\VariationMatrix::getVariations
...
vendor/magento/module-configurable-product/Model/Product/Type/Configurable.php::getConfigurableAttributesAsArray

'values' => $attribute->getOptions() ? $attribute->getOptions() : [],

vendor/magento/module-configurable-
product/Model/Product/Type/Configurable/Attribute.php::getOptions

```

I narrowed the issue to this;
https://github.com/magesuite/frontend/commit/3e19709602e85672605573ac927a6a149fdcbebe
It's a plugin on the original function:
`Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable::getAttributeOptions`.
The plugin excludes options because those are not in the sort array. It can happen. It did in my case.

This is in the database:
```
select * from eav_attribute_option where attribute_id=254;
+-----------+--------------+------------+
| option_id | attribute_id | sort_order |
+-----------+--------------+------------+
|      5453 |          254 |          0 |
|      5461 |          254 |          0 |
|      5467 |          254 |          0 |
|      5473 |          254 |          0 |
|      5479 |          254 |          0 |
|      5485 |          254 |          0 |
+-----------+--------------+------------+

select * from eav_attribute where attribute_code='size';
+--------------+----------------+----------------+-----------------+---------------+--------------+---------------+----------------+----------------+----------------+----------------+-------------------------------------------------+-------------+-----------------+---------------+-----------+------+
| attribute_id | entity_type_id | attribute_code | attribute_model | backend_model | backend_type | backend_table | frontend_model | frontend_input | frontend_label | frontend_class | source_model                                    | is_required | is_user_defined | default_value | is_unique | note |
+--------------+----------------+----------------+-----------------+---------------+--------------+---------------+----------------+----------------+----------------+----------------+-------------------------------------------------+-------------+-----------------+---------------+-----------+------+
|          254 |              4 | size           | NULL            | NULL          | int          | NULL          | NULL           | select         | Size           | NULL           | Magento\Eav\Model\Entity\Attribute\Source\Table |           0 |               1 |               |         0 | NULL |
+--------------+----------------+----------------+-----------------+---------------+--------------+---------------+----------------+----------------+----------------+----------------+-------------------------------------------------+-------------+-----------------+---------------+-----------+------+
```

Thank you

**Comment by daniel-ifrim** [comment] 2020-05-15 12:21
I used the patch bellow to fix the issue.
I am keeping the items that fail the IF condition:
`if(!isset($sortOrder[$item['value_index']]))`
in `$addItem`.
Than I add all items back into the final sorted array.
It's a temporary fix.

```
Index: htdocs/vendor/creativestyle/magesuite-frontend/Plugin/SortAttributeOptions.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- htdocs/vendor/creativestyle/magesuite-frontend/Plugin/SortAttributeOptions.php	(date 1589543242126)
+++ htdocs/vendor/creativestyle/magesuite-frontend/Plugin/SortAttributeOptions.php	(date 1589543242126)
@@ -40,17 +40,24 @@
         if(count($sortOrder)){

             $sortedItems = [];
+            $addItems = [];
             foreach($items AS $item){
-                if(!isset($sortOrder[$item['value_index']])) continue;
+               if(!isset($sortOrder[$item['value_index']]) || (isset($sortOrder[$item['value_index']]) && $sortOrder[$item['value_index']] <= 0)) {
+                    $addItems[] = $item;
+                    continue;
+                }
                 $itemPosition = $sortOrder[$item['value_index']];
                 $sortedItems[$itemPosition] = $item;
             }


             ksort($sortedItems);
+            foreach ($addItems as $item) {
+                $sortedItems[] = $item;
+            }
             return $sortedItems;
         }

         return $items;
     }
-}
\ No newline at end of file
+}

```

**Comment by diwipl** [comment] 2020-07-06 10:44
@daniel-ifrim can you provide us database dump or exact repro path how to reproduce such database condition on fresh environment ?

**Comment by daniel-ifrim** [comment] 2020-07-06 11:31
@diwipl No I can not do that sorry.

**Comment by krisdante** [comment] 2020-12-10 21:58
Closing due to no reproduction path.

**Closed as completed by krisdante** 2020-12-10 21:58 UTC
