### ISSUE TITLE
empty htmlClass attribute is not allowed in layout configuration

### ISSUE THREAD

**Issue by davidverholen** [magesuite/magesuite#4] opened 2019-06-05 16:56 UTC
**Description**:
Some layouts contain refereceneContainer elements with htmlClass=""
This is not allowed and the validation throws an error when loading for example the homepage

**Reproduce**:
1. install magento 2.3.1
2. set deployment mode to developer
3. install magesuite 2.0.1
4. install and activate creativeshop theme
5. clear cache and go to homepage

**Expected**:
The homepage should load

**Actual**:
An error is displayed

```
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 2028

Element 'referenceContainer', attribute 'htmlClass': '' is not a valid value of the atomic type 'htmlClassType'.
Line: 2028


Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 2028

Element 'referenceContainer', attribute 'htmlClass': '' is not a valid value of the atomic type 'htmlClassType'.
Line: 2028

<pre>#1 Magento\Framework\Config\Dom->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116]
#2 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]
#3 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/Config/DomFactory.php:43]
#5 Magento\Framework\Config\DomFactory->createDom() called at [vendor/magento/framework/View/Model/Layout/Update/Validator.php:141]
#6 Magento\Framework\View\Model\Layout\Update\Validator->isValid() called at [vendor/magento/framework/View/Model/Layout/Merge.php:476]
#7 Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout() called at [vendor/magento/framework/View/Model/Layout/Merge.php:457]
#8 Magento\Framework\View\Model\Layout\Merge->load() called at [generated/code/Magento/Framework/View/Model/Layout/Merge/Interceptor.php:193]
#9 Magento\Framework\View\Model\Layout\Merge\Interceptor->load() called at [vendor/magento/framework/View/Layout/Builder.php:86]
#10 Magento\Framework\View\Layout\Builder->loadLayoutUpdates() called at [vendor/magento/framework/View/Layout/Builder.php:63]
#11 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:253]
#12 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:875]
#13 Magento\Framework\View\Layout->getBlock() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:414]
#14 Magento\Framework\View\Layout\Interceptor->getBlock() called at [vendor/magento/module-cms/Helper/Page.php:171]
#15 Magento\Cms\Helper\Page->prepareResultPage() called at [vendor/magento/module-cms/Controller/Index/Index.php:74]
#16 Magento\Cms\Controller\Index\Index->execute() called at [generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php:24]
#17 Magento\Cms\Controller\Index\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#18 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#19 Magento\Cms\Controller\Index\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#20 Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#21 Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php:39]
#22 Magento\Cms\Controller\Index\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#23 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#24 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#25 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#26 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#27 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#28 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#29 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#30 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#31 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#32 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:136]
#33 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#34 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#35 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
#36 require() called at [/Users/david.verholen/.composer/vendor/weprovide/valet-plus/server.php:131]
</pre>

```

**Comment by diwipl** [comment] 2019-06-06 08:13
Thank you for your report, I've created internal ticket to resolve this issue.

**Comment by torhoehn** [comment] 2019-06-17 08:29
@diwipl I have the same problem. Is there any progress on this issue?

**Comment by seyuf** [comment] 2019-07-06 20:51
Removing htmlClass attribute from appropriate tags suffice to resolve the issue i.e:

```
./vendor/creativestyle/theme-creativeshop/src/Magento_Cms/layout/cms_page_view.xml:26:        <referenceContainer name="main.content" htmlClass="" />

./vendor/creativestyle/theme-creativeshop/src/MageSuite_ContentConstructor/layout/contentconstructor_components_index.xml:17:        <referenceContainer name="main.content" htmlClass="" />

./vendor/creativestyle/theme-creativeshop/src/Magento_Catalog/layout/catalog_product_view.xml:18:        <referenceContainer name="main.content" htmlClass="" />
```

Or in your theme (app/design) if it has already been generated i.e
`
./theme-creativeshop/Magento_Cms/layout/cms_page_view.xml:26:        <referenceContainer name="main.content" htmlClass="" />
./theme-creativeshop/MageSuite_ContentConstructor/layout/contentconstructor_components_index.xml:17:        <referenceContainer name="main.content" htmlClass="" />
./theme-creativeshop/Magento_Catalog/layout/catalog_product_view.xml:18:        <referenceContainer name="main.content" htmlClass="" />
`

**Comment by krisdante** [comment] 2019-07-07 18:56
Dear all,
We use this to actually remove the class with XML. Sometimes we need this and we patched Magento to support it. We also suggested this ad PR to Magento. 
For that reason removing the parameter will remove the error, but will also cause faulty results.

**Comment by krisdante** [comment] 2019-07-07 18:58
The problem is that our patches to Magento are not committed here nor available anywhere. I need to think how to solve this in best way.

**Comment by twosg** [comment] 2019-07-15 23:10
Maybe you can seperate it within a own module, until the PR is accepted?!

**Comment by krzksz** [comment] 2019-07-16 05:18
Hey, just wanted to let you know that we've just planned this issue for current sprint and will try to fix it as soon as possible.

**Comment by seyuf** [comment] 2019-07-16 15:15
Hi @krzksz,
i saw the fix for the htmlClass issue (htmlClass="none") in the creativeshop theme repo.
Seems to be working, unfortunately i also got this error on the group attribute:
`'referenceBlock', attribute 'group': The attribute 'group' is not allowed.`

**Comment by twosg** [comment] 2019-07-17 16:07
> Hi @krzksz,
> i saw the fix for the htmlClass issue (htmlClass="none") in the creativeshop theme repo.
> Seems to be working, unfortunately i also got this error on the group attribute:
> `'referenceBlock', attribute 'group': The attribute 'group' is not allowed.`

Same here. Errors happen on the product page, coming from vendor/creativestyle/theme-creativeshop/src/Magento_Catalog/layout/catalog_product_view.xml (and of course from app/design after build).

**Comment by krzksz** [comment] 2019-07-18 09:32
Empty `htmlClass` was fixed in https://github.com/magesuite/theme-creativeshop/commit/d0110463bf223764af9673314c3b892f9babd698

In terms of `group` attribute there is already an issue and progress will be tracked there: https://github.com/magesuite/theme-creativeshop/issues/2

**Closed as completed by krzksz** 2019-07-18 09:32 UTC

**Comment by jtomaszewski** [comment] 2020-04-19 13:55
Do you know any workaround so that turning on developer mode is possible with magesuite?

Developing extensions in production mode (e.g. that swallows PHP errors) is terrible ;/

--- EDIT --- 

Nevermind, somehow I enabled it now at my magento and it just works.

**Comment by krzksz** [comment] 2020-04-19 14:12
We are actually using `default` mode for development as a sweet spot.
